const KEY='oab_focus_personal_v5';
export const blankState=()=>({attempts:{},favorites:[],notes:{},completedWeeks:[],xp:0,lastStudyAt:null,settings:{dailyGoal:20,shuffle:true},simulations:{}});
export function loadLocal(){try{return {...blankState(),...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return blankState()}}
export function saveLocal(s){localStorage.setItem(KEY,JSON.stringify(s))}
export function mergeState(local,cloud){if(!cloud)return local;return {...blankState(),...local,...cloud,attempts:{...(local.attempts||{}),...(cloud.attempts||{})},notes:{...(local.notes||{}),...(cloud.notes||{})},favorites:[...new Set([...(local.favorites||[]),...(cloud.favorites||[])])],completedWeeks:[...new Set([...(local.completedWeeks||[]),...(cloud.completedWeeks||[])])].sort((a,b)=>a-b),settings:{...blankState().settings,...local.settings,...cloud.settings}}}
export function recordAttempt(s,qid,selected,answer,seconds){const prev=s.attempts[qid]||{count:0,history:[]};const item={selected,correct:selected===answer,seconds,at:new Date().toISOString()};s.attempts[qid]={count:(prev.count||0)+1,last:item,history:[...(prev.history||[]).slice(-9),item]};s.xp=(s.xp||0)+(item.correct?15:5);s.lastStudyAt=item.at;saveLocal(s);return item}
export function toggleFavorite(s,id){const x=new Set(s.favorites||[]);x.has(id)?x.delete(id):x.add(id);s.favorites=[...x];saveLocal(s)}
export function saveNote(s,id,text){s.notes[id]=text;saveLocal(s)}
export function toggleWeek(s,w){const x=new Set(s.completedWeeks||[]);x.has(w)?x.delete(w):x.add(w);s.completedWeeks=[...x].sort((a,b)=>a-b);saveLocal(s)}
export function resetLocal(){const s=blankState();saveLocal(s);return s}
export function stats(s,qs){const rows=Object.entries(s.attempts||{}).filter(([,v])=>v?.last);const answered=rows.length,correct=rows.filter(([,v])=>v.last.correct).length;const totalAttempts=rows.reduce((n,[,v])=>n+(v.count||1),0);const secs=rows.reduce((n,[,v])=>n+(v.last.seconds||0),0);const map=new Map(qs.map(q=>[q.id,q]));const by={};for(const [id,v] of rows){const q=map.get(id);if(!q)continue;by[q.discipline]??={answered:0,correct:0};by[q.discipline].answered++;if(v.last.correct)by[q.discipline].correct++}return{answered,correct,accuracy:answered?Math.round(correct/answered*100):0,totalAttempts,avgSeconds:answered?Math.round(secs/answered):0,by}}
